INSERT INTO MAILING_SERVER(SERVER_ID, SERVER_NAME, SERVER_PROVIDER) VALUES(1, 'SRVCLDBEN001', 'AMAZON');
INSERT INTO MAILING_SERVER(SERVER_ID, SERVER_NAME, SERVER_PROVIDER) VALUES(2, 'SRVCLDBEN002', 'Digital Ocean');

--INSERT INTO MAILING_MTA(MTA_ID, MTA_NAME, MTA_DNS, MTA_IP,MTA_PORT, MTA_USERNAME, MTA_PASSWORD, MTA_SERVER_ID) VALUES(1, 'V_MTA1', 'DNS1',  '192.168.0.1', '587', 'user1','12345', 1);
--INSERT INTO MAILING_MTA(MTA_ID, MTA_NAME, MTA_DNS, MTA_IP,MTA_PORT, MTA_USERNAME, MTA_PASSWORD, MTA_SERVER_ID) VALUES(2, 'V_MTA2', 'DNS2',  '192.168.0.2', '587', 'user2','pass1', 1);
--INSERT INTO MAILING_MTA(MTA_ID, MTA_NAME, MTA_DNS, MTA_IP,MTA_PORT, MTA_USERNAME, MTA_PASSWORD, MTA_SERVER_ID) VALUES(3, 'V_MTA_X', 'DNS3', '192.168.0.3', '587', 'user3','Ok', 2);

INSERT INTO MAILING_MTA(MTA_ID, MTA_NAME, MTA_DNS, MTA_IP,MTA_PORT, MTA_USERNAME, MTA_PASSWORD, MTA_SERVER_ID) VALUES(1, 'mailtrap', 'smtp.mailtrap.io', null, '587', '1f8ddaa0ad6d5d','b54cc5bc6aced8', 1);